### ISSUE TITLE
Numerous deprecation warnings and {{on-key "shift+ any"}} not working on Mac

### ISSUE THREAD

**Issue by akankshadharkar** [adopted-ember-addons/ember-keyboard#410]
<img width="838" alt="Screen Shot 2021-05-24 at 4 54 46 PM" src="https://user-images.githubusercontent.com/12375430/119420205-c298ec80-bcb0-11eb-8afe-55a4efcb2f6e.png">

**Comment by SergeAstapov** [comment]
@akankshadharkar could you please try latest v6.0.4?

all the necessary fixes for proper `deprecate` function usage were fixed in v6.0.3 so you should not see any warnings about missing `for` and `since` arguments.

Regarding `ember-keyboard-first-responder-inputs` initializer - it's legit deprecation warning:
* if you don't rely on the functionality provided by the initializer, disable the initializer (and the warning) by setting `emberKeyboard.disableInputsInitializer` in the `config/environment.js` to `true`
* if you don't rely on the functionality provided by the initializer, please refactor away.

For more info about `ember-keyboard-first-responder-inputs` deprecation please see http://adopted-ember-addons.github.io/ember-keyboard/deprecations#first-responder-inputs
